# Generated by Django 3.1.5 on 2021-01-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
            ],
        ),
    ]
